services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_HOST=database
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=myuser
  #     - DATABASE_PASSWORD=mypassword
  #     - DATABASE_NAME=mydb
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - database
  #   command: yarn start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8444:8444"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # - /usr/share/nginx/html:/usr/share/nginx/html

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/dbus:/var/run/dbus  # Доступ до D-Bus
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    privileged: true  # Дозволяє доступ до Bluetooth-адаптера
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  # database:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
