services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8444:8444"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/dbus:/var/run/dbus  # Доступ до D-Bus
      - sqlite_data:/app/data
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    privileged: true  # Дозволяє доступ до Bluetooth-адаптера
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped

volumes:
  sqlite_data:
