1001:
  message: "Критичний рівень заряду батареї: менше 10%. Можливе автоматичне вимкнення батареї."
  description: ""
  level: "critical"

1002:
  message: "Низький рівень заряду батареї: менше 20%."
  description: ""
  level: "error"

1003:
  message: "Низький рівень заряду: менше 30%. Жодного джерела заряджання не виявлено."
  description: ""
  level: "warning"

1004:
  message: "Розбаланс між осередками перевищує 0.1 V. Необхідна негайна балансування."
  description: "Значення знаходяться у змінній voltage_difference."
  level: "critical"

1005:
  message: "Розбаланс між осередками перевищує 0.05 V. Необхідна негайна балансування."
  description: "Значення знаходяться у змінній voltage_difference."
  level: "error"

1006:
  message: "Середня напруга осередків менше 3.0 V. Значення поза нормальним діапазоном може призвести до пошкодження батареї."
  description: "Значення знаходяться у змінній average_voltage."
  level: "critical"

1007:
  message: "Середня напруга осередків менше 3.2 V. Значення поза нормальним діапазоном може призвести до пошкодження батареї."
  description: "Значення знаходяться у змінній average_voltage."
  level: "error"

1008:
  message: "Середня напруга осередків перевищує 4.2 V. Значення поза нормальним діапазоном може пошкодити батарею."
  description: "Значення знаходяться у змінній average_voltage."
  level: "critical"

1009:
  message: "Середня напруга осередків перевищує 4.1 V. Значення поза нормальним діапазоном може пошкодити батарею."
  description: "Значення знаходяться у змінній average_voltage."
  level: "error"

1010:
  message: "Температура батареї перевищила 60°C, що може спричинити перегрів."
  description: "Значення знаходяться у змінних temperature_sensor_1-5."
  level: "critical"

1011:
  message: "Температура батареї перевищила 50°C, що може спричинити перегрів."
  description: "Значення знаходяться у змінних temperature_sensor_1-5."
  level: "error"

1012:
  message: "Високий струм зарядки перевищив 100 A, що може спричинити перегрів або пошкодження."
  description: "Значення знаходиться у змінній charge_current."
  level: "critical"

1013:
  message: "Високий струм зарядки перевищив 80 A, що може спричинити перегрів або пошкодження."
  description: "Значення знаходиться у змінній charge_current."
  level: "error"

1014:
  message: "Високий струм розрядки перевищив -100 A, що може спричинити перегрів або пошкодження."
  description: "Значення знаходиться у змінній charge_current."
  level: "critical"

1015:
  message: "Високий струм розрядки перевищив -80 A, що може спричинити перегрів або пошкодження."
  description: "Значення знаходиться у змінній charge_current."
  level: "error"

1016:
  message: "Загальний стан батареї (SOH) впав нижче 90%, що свідчить про значну деградацію."
  description: "Значення знаходиться у змінній state_of_health."
  level: "critical"

1017:
  message: "Загальний стан батареї (SOH) впав нижче 80%, що свідчить про значну деградацію."
  description: "Значення знаходиться у змінній state_of_health."
  level: "error"

1018:
  message: "Високий опір осередків перевищив 0.5 Ом, що може свідчити про проблему в конкретному осередку."
  description: "Значення знаходиться у змінній cell_resistances."
  level: "critical"

1019:
  message: "Високий опір осередків перевищив 0.3 Ом, що може свідчити про проблему в конкретному осередку."
  description: "Значення знаходиться у змінній cell_resistances."
  level: "error"

1020:
  message: "Загальна напруга батареї перевищила 60 V. Вихід за межі нормального діапазону може спричинити пошкодження батареї або пристроїв."
  description: "Значення знаходиться у змінній battery_voltage."
  level: "critical"

1021:
  message: "Загальна напруга батареї перевищила 58 V. Вихід за межі нормального діапазону може спричинити пошкодження батареї або пристроїв."
  description: "Значення знаходиться у змінній battery_voltage."
  level: "error"

1022:
  message: "Загальна напруга батареї впала до 40 V або менше. Вихід за межі нормального діапазону може спричинити пошкодження батареї або пристроїв."
  description: "Значення знаходиться у змінній battery_voltage."
  level: "critical"

1023:
  message: "Загальна напруга батареї впала до 44 V або менше. Вихід за межі нормального діапазону може спричинити пошкодження батареї або пристроїв."
  description: "Значення знаходиться у змінній battery_voltage."
  level: "error"

1024:
  message: "Час до аварійного відключення менше ніж 5 хв. Рекомендується негайно з’ясувати причини."
  description: "Значення знаходиться у змінній emergency_time_countdown."
  level: "critical"

1025:
  message: "Час до аварійного відключення менше ніж 10 хв. Рекомендується негайно з’ясувати причини."
  description: "Значення знаходиться у змінній emergency_time_countdown."
  level: "error"

1026:
  message: "Кількість циклів заряд/розряд перевищила 2000. Ефективність батареї знижується."
  description: "Значення знаходиться у змінній cycle_count."
  level: "warning"

1027:
  message: "Кількість циклів заряд/розряд перевищила 1500. Ефективність батареї знижується."
  description: "Значення знаходиться у змінній cycle_count."
  level: "warning"
